org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false

kotlin.code.style=official
kotlin.incremental=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
