package com.wanted.android.wanted.design.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
import com.wanted.android.designsystem.R

val pretendard = FontFamily(
    Font(R.font.regular, FontWeight.W400),
    Font(R.font.medium, FontWeight.W500),
    Font(R.font.semi_bold, FontWeight.W600),
)

val pretendardBold = FontFamily(
    Font(R.font.regular, FontWeight.W400),
    Font(R.font.medium, FontWeight.W500),
    Font(R.font.bold, FontWeight.W700),
)

@Immutable
data class WantedTypography(
    val display1Regular: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 56.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = (-0.0319).em,
        lineHeight = 72.sp,
    ),
    val display1Medium: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 56.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = (-0.0319).em,
        lineHeight = 72.sp,
    ),
    val display1Bold: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 56.sp,
        fontWeight = FontWeight.W700,
        letterSpacing = (-0.0319).em,
        lineHeight = 72.sp,
    ),
    val display2Regular: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 40.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = (-0.0282).em,
        lineHeight = 52.sp,
    ),
    val display2Medium: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 40.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = (-0.0282).em,
        lineHeight = 52.sp,
    ),
    val display2Bold: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 40.sp,
        fontWeight = FontWeight.W700,
        letterSpacing = (-0.0282).em,
        lineHeight = 52.sp,
    ),
    val title1Regular: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 36.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = (-0.027).em,
        lineHeight = 48.sp,
    ),
    val title1Medium: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 36.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = (-0.027).em,
        lineHeight = 48.sp,
    ),
    val title1Bold: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 36.sp,
        fontWeight = FontWeight.W700,
        letterSpacing = (-0.027).em,
        lineHeight = 48.sp,
    ),
    val title2Regular: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 28.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = (-0.0236).em,
        lineHeight = 38.sp,
    ),
    val title2Medium: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 28.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = (-0.0236).em,
        lineHeight = 38.sp,
    ),
    val title2Bold: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 28.sp,
        fontWeight = FontWeight.W700,
        letterSpacing = (-0.0236).em,
        lineHeight = 38.sp,
    ),
    val title3Regular: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 24.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = (-0.023).em,
        lineHeight = 32.sp,
    ),
    val title3Medium: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 24.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = (-0.023).em,
        lineHeight = 32.sp,
    ),
    val title3Bold: TextStyle = TextStyle(
        fontFamily = pretendardBold,
        fontSize = 24.sp,
        fontWeight = FontWeight.W700,
        letterSpacing = (-0.023).em,
        lineHeight = 32.sp,
    ),
    val heading1Regular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 22.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = (-0.0194).em,
        lineHeight = 30.sp,
    ),
    val heading1Medium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 22.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = (-0.0194).em,
        lineHeight = 30.sp,
    ),
    val heading1Bold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 22.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = (-0.0194).em,
        lineHeight = 30.sp,
    ),
    val heading2Regular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 20.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = (-0.012).em,
        lineHeight = 28.sp,
    ),
    val heading2Medium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 20.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = (-0.012).em,
        lineHeight = 28.sp,
    ),
    val heading2Bold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 20.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = (-0.012).em,
        lineHeight = 28.sp,
    ),
    val headline1Regular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 18.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = (-0.002).em,
        lineHeight = 26.sp,
    ),
    val headline1Medium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 18.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = (-0.002).em,
        lineHeight = 26.sp,
    ),
    val headline1Bold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 18.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = (-0.002).em,
        lineHeight = 26.sp,
    ),
    val headline2Regular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 17.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = 0.em,
        lineHeight = 24.sp,
    ),
    val headline2Medium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 17.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = 0.em,
        lineHeight = 24.sp,
    ),
    val headline2Bold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 17.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = 0.em,
        lineHeight = 24.sp,
    ),
    val body1Regular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 16.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = 0.0057.em,
        lineHeight = 24.sp,
    ),
    val body1Medium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 16.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = 0.0057.em,
        lineHeight = 24.sp,
    ),
    val body1Bold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 16.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = 0.0057.em,
        lineHeight = 24.sp,
    ),
    val body1ReadingRegular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 16.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = 0.0057.em,
        lineHeight = 26.sp,
    ),
    val body1ReadingMedium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 16.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = 0.0057.em,
        lineHeight = 26.sp,
    ),
    val body1ReadingBold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 16.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = 0.0057.em,
        lineHeight = 26.sp,
    ),
    val body2Regular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 15.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = 0.0096.em,
        lineHeight = 22.sp,
    ),
    val body2Medium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 15.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = 0.0096.em,
        lineHeight = 22.sp,
    ),
    val body2Bold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 15.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = 0.0096.em,
        lineHeight = 22.sp,
    ),
    val body2ReadingRegular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 15.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = 0.0096.em,
        lineHeight = 24.sp,
    ),
    val body2ReadingMedium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 15.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = 0.0096.em,
        lineHeight = 24.sp,
    ),
    val body2ReadingBold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 15.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = 0.0096.em,
        lineHeight = 24.sp,
    ),
    val label1Regular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 14.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = 0.0145.em,
        lineHeight = 20.sp,
    ),
    val label1Medium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 14.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = 0.0145.em,
        lineHeight = 20.sp,
    ),
    val label1Bold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 14.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = 0.0145.em,
        lineHeight = 20.sp,
    ),
    val label1ReadingRegular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 14.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = 0.0145.em,
        lineHeight = 22.sp,
    ),
    val label1ReadingMedium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 14.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = 0.0145.em,
        lineHeight = 22.sp,
    ),
    val label1ReadingBold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 14.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = 0.0145.em,
        lineHeight = 22.sp,
    ),
    val label2Regular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 13.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = 0.0194.em,
        lineHeight = 18.sp,
    ),
    val label2Medium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 13.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = 0.0194.em,
        lineHeight = 18.sp,
    ),
    val label2Bold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 13.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = 0.0194.em,
        lineHeight = 18.sp,
    ),
    val caption1Regular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 12.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = 0.0252.em,
        lineHeight = 16.sp,
    ),
    val caption1Medium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 12.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = 0.0252.em,
        lineHeight = 16.sp,
    ),
    val caption1Bold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 12.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = 0.0252.em,
        lineHeight = 16.sp,
    ),
    val caption2Regular: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 11.sp,
        fontWeight = FontWeight.W400,
        letterSpacing = 0.0311.em,
        lineHeight = 14.sp,
    ),
    val caption2Medium: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 11.sp,
        fontWeight = FontWeight.W500,
        letterSpacing = 0.0311.em,
        lineHeight = 14.sp,
    ),
    val caption2Bold: TextStyle = TextStyle(
        fontFamily = pretendard,
        fontSize = 11.sp,
        fontWeight = FontWeight.W600,
        letterSpacing = 0.0311.em,
        lineHeight = 14.sp,
    ),
)

val LocalWantedTypography = staticCompositionLocalOf { WantedTypography() }
