groupId=jobs.wanted.designsystem.doc
version=2
beforeVersion=1

## version ? beforeVersion ? ???? ??? ??? "??? api ???(mdx)" ?? ???
## mdx ?? ????? version? +1 ??? ci ?? ???.
## ??? ??? ??? document/source ? ??? ??? ???? mdx ?? ???.
## ??? ??? ??? document/md ? ?? mdx ?? ???.