name: CD
on:
  repository_dispatch:
    types: [ deploy ]

  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.WANTED_DEV_TOKEN }}

      - name: Set VersionInfo from publish.gradle
        id: version_info
        run: |
          grep "LIB_VERSION = " gradle/publish.gradle | \
          cut -d '=' -f2 | tr -d ' ' | \
          xargs -I {} echo "::set-output name=version_code::{}"

      - name: Print Version
        run: |
          echo ${{steps.version_info.outputs.version_code}}

      - name: Secrets to File
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'private.tar'
          fileDir: './'
          encodedString: ${{ secrets.PRIVATE_BASE64 }}

      - name: Extract private.tar
        run: |
          tar xzvf ./private.tar
          rm private.tar

      - name: build
        run: |
          ./gradlew :designsystem:build

      - name: publish
        run: |
          ./gradlew :designsystem:publishDeployPublicationToGithubPackagesRepository

      - name: Create & Push Tag
        run: |
          git config --local user.name "deploy-bot"
          git tag v${{steps.version_info.outputs.version_code}}
          git push origin --tags

      - uses: release-drafter/release-drafter@master
        with:
          version: ${{ steps.version_info.outputs.version_code }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
